### ISSUE TITLE
videos of LLaVA-NeXT-interleave

### ISSUE THREAD

**Issue by farewellthree** [LLaVA-VL/LLaVA-NeXT#101]
Hello, could you tell me which video datasets LLaVA-NeXT-interleave uses? It’s hard to determine where the videos come from just by the annotations; I can only recognize ActivityNet.

**Comment by ZrrSkywalker** [comment]
Thanks for your interest. In the M4-Instruct training data, we use the 300K videos from [LLaVA-Hound](https://huggingface.co/datasets/ShareGPTVideo/train_video_and_instruction/tree/main/train_300k). Pleases download this dataset and utilize our json for training.
