### ISSUE TITLE
Number of image and image placeholder inconsistent of the M4-Instruct-Data

### ISSUE THREAD

**Issue by laserwave** [LLaVA-VL/LLaVA-NeXT#107]
Hi, 

I find the number of image and image placeholder inconsistent in some instances of the M4-Instruct-Data. 

For example, there are two image placeholders and 4 image paths, which is not consistent. Shoule I just use the first two images?

`{"sample_id": 4756, "conversations": [{"from": "human", "value": "<image><image>\nWhat's the detailed difference between the 2 images? Please list in detail."}, {"from": "gpt", "value": "The differences between the images are as follows:\n\n1. In the second image, the person is wearing a sleeveless top, unlike the short-sleeved top in the first image.\n2. In the third image, the surfboard held by the person is red on the bottom, whereas in the previous images it was not red.\n3. In the fourth image, there is a shark fin visible in the water to the right of the person, which wasn't present in the earlier images."}], "image": ["MagicBrush/images/10955.jpg", "MagicBrush/images/10956.jpg", "MagicBrush/images/10957.jpg", "MagicBrush/images/10958.jpg"], "choice_list": null, "metadata": {"dataset": "MagicBrush-Diff", "split": "train", "num_sample": 4511, "task_instruction": "What's the difference between 2 images?", "question_type": "open-ended"}}`

By the way, the content is from https://huggingface.co/datasets/lmms-lab/M4-Instruct-Data/blob/main/m4_instruct_annotations.json updated on 2024/7/11.

**Comment by laserwave** [comment]
Another data format issue of twitter_post data source, which is easy to correct. The conversation roles are reversed.

`"conversations": [{"from": "gpt", "value": "Help me write a Twitter post considering the following images.\n<image><image>"}, {"from": "human", "value": "\"Embracing my quirks and finding joy in the little things! 🌈 Sometimes, it's all about finding someone who appreciates you for who you are, spikes and all. #LoveYourself #SpreadPositivity\""}]`

**Comment by FengLi-ust** [comment]
Hi, thanks for this question. We have updated the twiter data several days ago, please download a new one. For the data in MagicBrush, we will check the data and update later.

**Comment by ZrrSkywalker** [comment]
@laserwave Thanks for your patience! The data has been rectified.
