### ISSUE TITLE
Where to find multi-image training data?

### ISSUE THREAD

**Issue by jyC23333** [LLaVA-VL/LLaVA-NeXT#149]
Hi, I can only find a subset of  the image from the dataset in [huggingface](https://huggingface.co/datasets/lmms-lab/LLaVA-OneVision-Data)

And I don't find multi-image datas in the dataset. for example, tqa is a multi-image dataset, but the specific items in this dataset have only one image.

![image](https://github.com/user-attachments/assets/5cb0b400-4244-479b-b244-070a169d32d3)
![image](https://github.com/user-attachments/assets/4aa5a74a-9cd8-41b4-bfaa-2e97d412404c)

Did I use the dataset in a wrong way?

**Comment by Luodian** [comment]
It's in M4-Instruct. 

https://huggingface.co/datasets/lmms-lab/M4-Instruct-Data

**Comment by jyC23333** [comment]
Thanks so much.
