### ISSUE TITLE
Why can not the code inference with multi-gpu?

### ISSUE THREAD

**Issue by JinhuiYE** [LLaVA-VL/LLaVA-NeXT#154]
I can infer with single gpu but fail while CUDA_VISIBLE_DEVICES=0,1 

I have 8*A800 and try to run lava-onevision-qwen2-72b-ov model, here is a bug:

'''
LLaVA-NeXT/llava/model/llava_arch.py", line 363, in prepare_inputs_labels_for_multimodal
    image_feature = torch.cat((image_feature, self.model.image_newline[None]), dim=0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:0! (when checking argument for argument tensors in method wrapper_CUDA_cat)
'''

**Comment by SiniShell1** [comment]
I just faced the same problem as you and solved it by adding `device_map=accelerator.device` instead of the default value `auto` while loading the model: 
lm_tokenizer, lm_model, lm_image_processor, lm_max_length = load_pretrained_model("lmms-lab/llava-onevision-qwen2-0.5b-si", None, "llava_qwen", device_map=accelerator.device)

**Comment by JinhuiYE** [comment]
Yes, I had fixed it by replaying the line with "image_feature = torch.cat((image_feature, self.model.image_newline[None].to(image_feature.device), dim=0)"

**Comment by shalini-maiti** [comment]
> .to(image_feature.device)

Hello, how do you initialize the variable accelerator?

**Comment by JinhuiYE** [comment]
export OMP_NUM_THREADS=8
export NCCL_IB_DISABLE=0

export NCCL_IB_GID_INDEX=3
export NCCL_DEBUG=INFO

workspaceFolder=
cd ${workspaceFolder}
# Set environment variables

export PYTHONPATH="${workspaceFolder}:${PYTHONPATH}"
export NCCL_SOCKET_IFNAME="eth2"
# export CUDA_VISIBLE_DEVICES="1"

MID_RUN_NAME=llava-onevision-qwen2-7b-ov-lora-funetuning-coords-16frame #
output_path=${workspaceFolder}/checkpoints/Jinhui/Debug
# 检查文件夹是否存在，如果不存在就创建它
if [ ! -d ${output_path}/${MID_RUN_NAME} ]; then
  mkdir -p ${output_path}/${MID_RUN_NAME}
fi

# 将当前脚本复制到指定的输出路径
cp ./llava/scripts/train/finetune_onevision.sh ${output_path}/${MID_RUN_NAME}
# --mm_spatial_pool_mode "conv" \
#    --obs_type "dynamic" \
    # --batch_mode "train" \


LLM_VERSION="Qwen/Qwen2-7B-Instruct" 
# for 7b model we recommend bs=1, accum=2, 16 nodes, 128 gpus, lr=1e-5, warmup=0.03
# for 72b model we recommend bs=1, accum=1, 32 nodes, 256 gpus, lr=1e-5, warmup=0.03
LLM_VERSION_CLEAN="${LLM_VERSION//\//_}"
VISION_MODEL_VERSION="google/siglip-so400m-patch14-384"
VISION_MODEL_VERSION_CLEAN="${VISION_MODEL_VERSION//\//_}"


############### Pretrain ################
# --mm_tunable_parts="mm_vision_tower,mm_mlp_adapter,mm_language_model" \
PROMPT_VERSION="qwen_1_5"

BASE_RUN_NAME="llavanext-${VISION_MODEL_VERSION_CLEAN}-${LLM_VERSION_CLEAN}-mlp2x_gelu-pretrain_blip558k_plain"
echo "BASE_RUN_NAME: ${BASE_RUN_NAME}"

CKPT_PATH=$LLM_VERSION # this could also be the previous stage checkpoint
    # --search_heuristic_header "2" \
ACCELERATE_CPU_AFFINITY=1 torchrun --nproc_per_node=1 --nnodes=2 --node_rank=0 \
    llava/train/train_localization.py \
    --deepspeed ./scripts/video/train/zero3.json \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 5e-5 \
    --model_name_or_path "${workspaceFolder}/pretrained/llava-onevision-qwen2-0.5b-ov" \
    --version qwen_1_5 \
    --data_path "playground/data/Ego4D/ego4d_rule_trajs/Search_Trajectory/nlq_train_binary_search.json" \
    --batch_mode "train" \
    --num_frames "4" \
    --obs_type "dynamic" \
    --video_folder "./playground/data/Ego4D/ego4d_data/v1/256p" \
    --image_folder ./onevision_data/images \
    --mm_tunable_parts="mm_mlp_adapter,search_heuristic_head" \
    --mm_vision_tower_lr=2e-6 \
    --vision_tower ./pretrained/siglip-so400m-patch14-384 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --group_by_modality_length True \
    --image_aspect_ratio anyres_max_9 \
    --image_grid_pinpoints  "(1x1),...,(6x6)" \
    --mm_patch_merge_type spatial_unpad \
    --bf16 True \
    --run_name $MID_RUN_NAME \
    --output_dir "${output_path}/${MID_RUN_NAME}" \
    --num_train_epochs 40000 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 680000 \
    --save_total_limit 1 \
    --learning_rate 1e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 32768 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb \
    --torch_compile True \
    --torch_compile_backend "inductor" \
    --dataloader_drop_last True \
    --frames_upbound 4

# You can delete the sdpa attn_implementation if you want to use flash attn

**Comment by zyandtom** [comment]
> ```
> export OMP_NUM_THREADS=8
> export NCCL_IB_DISABLE=0
> 
> export NCCL_IB_GID_INDEX=3
> export NCCL_DEBUG=INFO
> 
> workspaceFolder=
> cd ${workspaceFolder}
> # Set environment variables
> 
> export PYTHONPATH="${workspaceFolder}:${PYTHONPATH}"
> export NCCL_SOCKET_IFNAME="eth2"
> # export CUDA_VISIBLE_DEVICES="1"
> 
> MID_RUN_NAME=llava-onevision-qwen2-7b-ov-lora-funetuning-coords-16frame #
> output_path=${workspaceFolder}/checkpoints/Jinhui/Debug
> # 检查文件夹是否存在，如果不存在就创建它
> if [ ! -d ${output_path}/${MID_RUN_NAME} ]; then
>   mkdir -p ${output_path}/${MID_RUN_NAME}
> fi
> 
> # 将当前脚本复制到指定的输出路径
> cp ./llava/scripts/train/finetune_onevision.sh ${output_path}/${MID_RUN_NAME}
> # --mm_spatial_pool_mode "conv" \
> #    --obs_type "dynamic" \
>     # --batch_mode "train" \
> 
> 
> LLM_VERSION="Qwen/Qwen2-7B-Instruct" 
> # for 7b model we recommend bs=1, accum=2, 16 nodes, 128 gpus, lr=1e-5, warmup=0.03
> # for 72b model we recommend bs=1, accum=1, 32 nodes, 256 gpus, lr=1e-5, warmup=0.03
> LLM_VERSION_CLEAN="${LLM_VERSION//\//_}"
> VISION_MODEL_VERSION="google/siglip-so400m-patch14-384"
> VISION_MODEL_VERSION_CLEAN="${VISION_MODEL_VERSION//\//_}"
> 
> 
> ############### Pretrain ################
> # --mm_tunable_parts="mm_vision_tower,mm_mlp_adapter,mm_language_model" \
> PROMPT_VERSION="qwen_1_5"
> 
> BASE_RUN_NAME="llavanext-${VISION_MODEL_VERSION_CLEAN}-${LLM_VERSION_CLEAN}-mlp2x_gelu-pretrain_blip558k_plain"
> echo "BASE_RUN_NAME: ${BASE_RUN_NAME}"
> 
> CKPT_PATH=$LLM_VERSION # this could also be the previous stage checkpoint
>     # --search_heuristic_header "2" \
> ACCELERATE_CPU_AFFINITY=1 torchrun --nproc_per_node=1 --nnodes=2 --node_rank=0 \
>     llava/train/train_localization.py \
>     --deepspeed ./scripts/video/train/zero3.json \
>     --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 5e-5 \
>     --model_name_or_path "${workspaceFolder}/pretrained/llava-onevision-qwen2-0.5b-ov" \
>     --version qwen_1_5 \
>     --data_path "playground/data/Ego4D/ego4d_rule_trajs/Search_Trajectory/nlq_train_binary_search.json" \
>     --batch_mode "train" \
>     --num_frames "4" \
>     --obs_type "dynamic" \
>     --video_folder "./playground/data/Ego4D/ego4d_data/v1/256p" \
>     --image_folder ./onevision_data/images \
>     --mm_tunable_parts="mm_mlp_adapter,search_heuristic_head" \
>     --mm_vision_tower_lr=2e-6 \
>     --vision_tower ./pretrained/siglip-so400m-patch14-384 \
>     --mm_projector_type mlp2x_gelu \
>     --mm_vision_select_layer -2 \
>     --mm_use_im_start_end False \
>     --mm_use_im_patch_token False \
>     --group_by_modality_length True \
>     --image_aspect_ratio anyres_max_9 \
>     --image_grid_pinpoints  "(1x1),...,(6x6)" \
>     --mm_patch_merge_type spatial_unpad \
>     --bf16 True \
>     --run_name $MID_RUN_NAME \
>     --output_dir "${output_path}/${MID_RUN_NAME}" \
>     --num_train_epochs 40000 \
>     --per_device_train_batch_size 1 \
>     --per_device_eval_batch_size 4 \
>     --gradient_accumulation_steps 2 \
>     --evaluation_strategy "no" \
>     --save_strategy "steps" \
>     --save_steps 680000 \
>     --save_total_limit 1 \
>     --learning_rate 1e-5 \
>     --weight_decay 0. \
>     --warmup_ratio 0.03 \
>     --lr_scheduler_type "cosine" \
>     --logging_steps 1 \
>     --tf32 True \
>     --model_max_length 32768 \
>     --gradient_checkpointing True \
>     --dataloader_num_workers 4 \
>     --lazy_preprocess True \
>     --report_to wandb \
>     --torch_compile True \
>     --torch_compile_backend "inductor" \
>     --dataloader_drop_last True \
>     --frames_upbound 4
> 
> # You can delete the sdpa attn_implementation if you want to use flash attn
> ```

But seems like it's a train script.

**Comment by JinhuiYE** [comment]
```
export PYTHONPATH=${workspaceFolder}/:${PYTHONPATH}
cd ${workspaceFolder}
CUDA_VISIBLE_DEVICES=0,1,2,3 python ./llava/eval/EgoSchema/model_LongvideoBench.py

```

**Comment by zyandtom** [comment]
> ```
> export PYTHONPATH=${workspaceFolder}/:${PYTHONPATH}
> cd ${workspaceFolder}
> CUDA_VISIBLE_DEVICES=0,1,2,3 python ./llava/eval/EgoSchema/model_LongvideoBench.py
> 
> ```

Thx, can I have a look for model_LongvideoBench.py? This is what I want to know, very appreciated!
