### ISSUE TITLE
Installation of LLaVA Next dependency with package not found issue

### ISSUE THREAD

**Issue by haozhang1234** [LLaVA-VL/LLaVA-NeXT#166]
I encountered an issue when installing the LLaVA Next dependency, and I couldn't find this package from pypi at all.Even if this package is commented out in the requirement (byted remote ikernel==0.4.8)
The other packages under this package will also report consecutive errors. In the end, it resulted in not being able to secure a package, and I hope to receive help. thank you！
![_QO4168GJ)U}E1VJ2%XZ0 C](https://github.com/user-attachments/assets/a3632f11-cd9e-48e6-a86b-0ac71d58019d)

**Comment by stdereka** [comment]
Hi! Installing the package with dependencies from `pyproject.toml` works just fine.

**Comment by TJ-Ouyang** [comment]
> Hi! Installing the package with dependencies from `pyproject.toml` works just fine.

It doesn't work for me. I used "python -m pip install ."

**Comment by seandkim** [comment]
I got the same error before I realized README says use conda for downloading the packages. Are you following these steps in the README?

```bash
conda create -n llava python=3.10 -y
conda activate llava
pip install --upgrade pip  # Enable PEP 660 support.
pip install -e ".[train]"
```

**Comment by orzgugu** [comment]
Hi! This problem still exists and I cannot install the byted-remote-ikernel package. I installed poetry via pip install poetry and the problem still exists. I hope to get your help and look forward to your reply.

**Comment by copperwiring** [comment]
Same issue.

**Comment by ixn3rd3mxn** [comment]
Same issue too

![{E9C63D4F-4B51-49F6-BFCD-9CD710FE997A}](https://github.com/user-attachments/assets/0a017423-0152-4ee9-ac69-20aa7e6d41aa)

**Comment by ixn3rd3mxn** [comment]
> have you solved it ?

ayo, u can try 

pip install --upgrade pip
pip install -e .
pip install -e ".[train]"
conda install -c nvidia cuda-compiler
pip install gradio==3.35.2 flash-attn==2.5.7

it work on me , i use jupyter notebook in linux

**Comment by MengHao666** [comment]
> > have you solved it ?
> 
> ayo, u can try
> 
> pip install --upgrade pip pip install -e . pip install -e ".[train]" conda install -c nvidia cuda-compiler pip install gradio==3.35.2 flash-attn==2.5.7
> 
> it work on me , i use jupyter notebook in linux

thanks

**Comment by AllenLei666** [comment]
> > > have you solved it ?
> > 
> > 
> > ayo, u can try
> > pip install --upgrade pip pip install -e . pip install -e ".[train]" conda install -c nvidia cuda-compiler pip install gradio==3.35.2 flash-attn==2.5.7
> > it work on me , i use jupyter notebook in linux
> 
> thanks

Hi, there. I tried this. But still the same issue.

**Comment by ixn3rd3mxn** [comment]
> > > > have you solved it ?
> > > 
> > > 
> > > ayo, u can try
> > > pip install --upgrade pip pip install -e . pip install -e ".[train]" conda install -c nvidia cuda-compiler pip install gradio==3.35.2 flash-attn==2.5.7
> > > it work on me , i use jupyter notebook in linux
> > 
> > 
> > thanks
> 
> Hi, there. I tried this. But still the same issue.

1. already create conda venv?
2. ur pc already have gpu?
3. what ur gpu model?
4. ur cuda driver version?
