### ISSUE TITLE
UReader data (kg/qa) in llava-onevision-data does not match with images

### ISSUE THREAD

**Issue by khanrc** [LLaVA-VL/LLaVA-NeXT#168]
As discussed in https://huggingface.co/datasets/lmms-lab/LLaVA-OneVision-Data/discussions/5,
the ureader_kg and ureader_qa data are not matched with images.

I was able to recover 80-90% images by matching suffixes using `id` (adding ".png" or ".jpeg" to `id`), but still 10-20% images are not matched.

**Comment by Luodian** [comment]
Let me dig it, maybe uploaded wrong files..

**Comment by Luodian** [comment]
I re-upload the compressed images. Please download them again, sorry for the mistake, where I explained there, it's about an issue of not compressing with folder structure.

https://huggingface.co/datasets/lmms-lab/LLaVA-OneVision-Data/discussions/5

**Comment by khanrc** [comment]
Thanks, I checked that the updated dataset works well!
