### ISSUE TITLE
checkpoint for finetuning / datafile for finetuning

### ISSUE THREAD

**Issue by YerongLi** [LLaVA-VL/LLaVA-NeXT#182]
https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/scripts/train/finetune_onevision.sh

Is this the script for SFT? where can we find the folloing checkpoint for finetuning?

`"/checkpoints/projectors/${BASE_RUN_NAME}/mm_projector.bin" \`

Also, could anyone post a data preparation script for fine tuning?

**Comment by Luodian** [comment]
projector: https://huggingface.co/lmms-lab/llava-onevision-projectors

data preparation: We provide the data preparation script at our data repo (the hf one). 

we follow original llava data format, if you are not familiar with llava data format, recommend to check the repo: https://github.com/haotian-liu/LLaVA

**Comment by sc268** [comment]
Thanks @Luodian! Could you also share a sample of the`onevision_data.yaml` mentioned in the [finetuning script](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/scripts/train/finetune_onevision.sh#L28)?  Thanks!

**Comment by YerongLi** [comment]
where can we find the yaml file for `finetune_onevision.sh`? @Luodian 
> Thanks @Luodian! Could you also share a sample of the`onevision_data.yaml` mentioned in the [finetuning script](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/scripts/train/finetune_onevision.sh#L28)? Thanks!

```
 File "/home/yerong2/LLaVA-NeXT/llava/train/train.py", line 970, in __init__
    with open(data_path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: './onevision_data.yaml
```

**Comment by YerongLi** [comment]
@sc268  

> Thanks @Luodian! Could you also share a sample of the`onevision_data.yaml` mentioned in the [finetuning script](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/scripts/train/finetune_onevision.sh#L28)? Thanks!

They provide the yaml file here.
