### ISSUE TITLE
The infer script does not exist in the project

### ISSUE THREAD

**Issue by Jiangfan321** [LLaVA-VL/LLaVA-NeXT#19]
Thanks for your work. When I ran the inference script 'video_detail_description_eval_shard.sh' .I didn't find llava/eval/evaluate_benchmark_video_detail_description.py. I wonder if it's because I'm missing some steps?

**Comment by ZhangYuanhan-AI** [comment]
You can get this python at :https://github.com/LLaVA-VL/LLaVA-NeXT/tree/video_inference/llava/eval

**Comment by Jiangfan321** [comment]
> You can get this python file at :https://github.com/LLaVA-VL/LLaVA-NeXT/tree/video_inference/llava/eval

thank you! Wish you a happy life.
