### ISSUE TITLE
Request for Open Sourcing Post-Training Data and Clarification on Additional 100K Data for Video version

### ISSUE THREAD

**Issue by patrick-tssn** [LLaVA-VL/LLaVA-NeXT#2]
Thank you for your valuable contributions. Could you please consider making your post-training data available as open source? Additionally, could you clarify what constitutes the additional 100k+17k data points when compared to the image-based version?

**Comment by ZhangYuanhan-AI** [comment]
1. The dataset is: https://huggingface.co/datasets/MBZUAI/VideoInstruct-100K

**Comment by patrick-tssn** [comment]
Thank you.

**Comment by thunderbird0902** [comment]
the acitvitynet video data is hard to download, could you help to provide other link such as baiduyun?
