### ISSUE TITLE
location of llava_1_6.json

### ISSUE THREAD

**Issue by starhiking** [LLaVA-VL/LLaVA-NeXT#222]
Where is the llava_1_6.json referred to in the `scripts/train/finetune_clip.sh`

**Comment by mylesgoose** [comment]
i think you need to find what datasets you want to train your model with.
and run a script to get the data and generate the json file for that dataset.
for example:/home/myles/LLaVA-NeXT/LLaVA-ReCap-558K.json
/home/myles/LLaVA-NeXT/LLaVA-ReCap-CC3M.json
import os
from datasets import load_dataset
from tqdm import tqdm
import json

data = load_dataset("lmms-lab/LLaVA-ReCap-558K", split="train")

image_folder = "./data/image"

converted_data = []

for da in tqdm(data):
    json_data = {}
    json_data["id"] = da["id"]
    if da["image"] is not None:
        json_data["image"] = f"{da['id']}.jpg"
        da["image"].save(os.path.join(image_folder, json_data["image"]))
    json_data["conversations"] = da["conversations"]
    converted_data.append(json_data)

with open("LLaVA-ReCap-558K.json", "w") as f:
    json.dump(converted_data, f, indent=4, ensure_ascii=False)


 for example:that script downloasdsthat particular dataset from hugginface. it looks like yoru trying to train 1.6 i think perhaps all that is contained int he recap one below. probbaly have to go and find out what datasets 1.6 was trained on.
i noticed thsi guy has collated all the datasets into one json for you for the 1.6 model. 
https://github.com/xiaoachen98/Open-LLaVA-NeXT/blob/master/scripts/v1_6/train/8b/finetune.sh
in this docuemnt he explaisn hwo he prepared the data.
https://github.com/xiaoachen98/Open-LLaVA-NeXT/blob/master/docs/Data.md
i think perhaps this repo assumes you have followed the 1.5 and 1.6 github pages. 
datasets:
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llava_next_fit_mix_filtered_text_wild_738590.json # released in lmms-lab/LLaVA-NeXT-Data
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llava_wild_4v_39k.json # not released
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llava_wild_4v_12k.json # not released
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llavar_gpt4_20k.json
    sampling_strategy: "all"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sroie_data_33626.json
  #   sampling_strategy: "first:10%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/orand_car_a_train_2009.json
  #   sampling_strategy: "all"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/orand_car_b_train_3000.json
  #   sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/mavis_math_metagen_87358.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/mavis_math_rule_geo_100000.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/chrome_writting_train_8835.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/k12_printing_train_256646.json
    sampling_strategy: "first:1%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/iiit5k_annotations_2000.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/hme100k_train_clean_74502.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/ai2d_azuregpt_detailed_understanding_4874.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/infographic_vqa_4404.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/infographic_azuregpt4v_1992.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/lrv_chart_1787.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/lrv_normal_gpt4v_filtered_10500.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/scienceqa_nona_context_19218.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/allava_instruct_vflan4v_20000.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/allava_instruct_laion4v_50000.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/textocr_gpt4v_train_converted_25114.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/ai2d_train_internvl_single_12413.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/textcaps_train_21952.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_new/ureader_qa_sft.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_new/ureader_cap_sft.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_new/ureader_ie_sft.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_new/ureader_kg_sft.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/vision_flan_filtered_186070.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/mathqa_29837.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/geo3k_2101.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/geo170k_qa_converted_67833.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/geo170k_align_converted_60252.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4v-coco-50k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4v-knowledge-2k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4v-llava-30k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4v-sam-20k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_CLEVR-Math_5290.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_FigureQA_17597.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_Geometry3K_9734.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_GeoQA+_17172.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_GEOS_508.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_IconQA_22599.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_MapQA_5235.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_PMC-VQA_35958.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_Super-CLEVR_8652.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_TabMWP_22462.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_TQA_10181.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_UniGeo_11959.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_VizWiz_6614.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_VQA-AS_5907.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_VQA-RAD_2130.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/Evol-Instruct-GPT4-Turbo-143000.json
    sampling_strategy: "first:30%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/magpie_pro_qwen2_72b_st_300000_sp_token_fltd_299992.json
    sampling_strategy: "first:50%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/magpie_pro_l3_80b_st_300000.json
    sampling_strategy: "first:50%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/magpie_pro_l3_80b_mt_300000_sp_token_fltd_299998.json
    sampling_strategy: "first:50%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/image_textualization_dataset_filtered.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/cambrian_filtered_gpt4vo_sp_token_fltd_max10k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4o_dataset.jsonl
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/ai2d_llava_format_2434.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/aokvqa_16539_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/chart2text_26961.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/chartqa_18265_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/clevr_70000_llava_format.json
    sampling_strategy: "first:1%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/diagram_image_to_text_300.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/dvqa_200000_llava_format.json
    sampling_strategy: "first:1%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/figureqa_100000_llava_format.json
    sampling_strategy: "first:1%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/geomverse_9303.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/hateful_memes_8500_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/hitab_2500_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/iam_5663.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/raven_42000.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/iconqa_llava_format_27307.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/infographic_vqa_2118_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/intergps_1280_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/mapqa_37417_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/multihiertt_7619.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/rendered_text_10000.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/robut_sqa_8514.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/robut_wikisql_74989.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/robut_wtq_38246_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/screen2words_15730.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/scienceqa_llava_format_4976.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/tabmwp_22722.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/tallyqa_98680_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/st_vqa_17247_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/tqa_llava_format_27307.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/visual7w_llava_format_14366.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/visualmrc_3027.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/vqarad_313_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/vsr_2157_llava_format.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/vistext_9969.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/websight_10000.json
    sampling_strategy: "all"
datasets:
  - json_path: /mnt/bn/vl-research/data/llava_instruct/blip558k_stage1.5_finetune_w_prompt.json # released in lmms-lab/LLaVA-ReCap-*
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/coco118k_stage1.5_finetune_w_prompt.json # released in lmms-lab/LLaVA-ReCap-*
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cc3m_recap_data_prompt_v2.json # released in lmms-lab/LLaVA-ReCap-*
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_tr_sft.json # released in lmms-lab/LLaVA-OneVision-Mid-Data
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/instruct_azure_dc_zh_92K.json # not released, explained at https://github.com/LLaVA-VL/LLaVA-NeXT/tree/main/scripts/train
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/Evol-Instruct-GPT4-Turbo-143K.json # released in lmms-lab/LLaVA-OneVision-Mid-Data
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/synthdog_zh/synthdog_zh_100k.json # released in lmms-lab/LLaVA-OneVision-Mid-Data
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/synthdog_en/synthdog_en_100k.json # released in lmms-lab/LLaVA-OneVision-Mid-Data
    sampling_strategy: all
datasets:
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llava_next_fit_mix_filtered_text_wild_738590.json
    sampling_strategy: "first:50%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llava_wild_4v_39k.json # not released
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llava_wild_4v_12k.json # not released
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/mavis_math_metagen_87358.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/mavis_math_rule_geo_100000.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/cambrian_filtered_gpt4vo_sp_token_fltd_max10k_checked.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/VisualWebInstruct_filtered_263589.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/visual_chat_en_26048_gpt4o_coco_checked.json # not released
    sampling_strategy: "all"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/gpt4o_combinations_51316.json
  #   sampling_strategy: "all"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/chrome_writting_train_8835.json
  #   sampling_strategy: "first:20%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/k12_printing_train_256646.json
  #   sampling_strategy: "first:1%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/iiit5k_annotations_2000.json
  #   sampling_strategy: "first:20%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/hme100k_train_clean_74502.json
  #   sampling_strategy: "first:10%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sroie_data_33626.json
  #   sampling_strategy: "first:1%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/orand_car_a_train_2009.json
  #   sampling_strategy: "first:10%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/orand_car_b_train_3000.json
  #   sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llavar_gpt4_20k.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/ai2d_azuregpt_detailed_understanding_4874.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/infographic_vqa_4404.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/infographic_azuregpt4v_1992.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/lrv_chart_1787.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/lrv_normal_gpt4v_filtered_10500.json
    sampling_strategy: "first:10%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/scienceqa_nona_context_19218.json
  #   sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/allava_instruct_vflan4v_20000.json
    sampling_strategy: "first:30%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/allava_instruct_laion4v_50000.json
    sampling_strategy: "first:30%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/textocr_gpt4v_train_converted_25114.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/ai2d_train_internvl_single_12413.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/textcaps_train_21952.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_new/ureader_qa_sft.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_new/ureader_cap_sft.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_new/ureader_ie_sft.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/ureader_new/ureader_kg_sft.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/vision_flan_filtered_186070.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/mathqa_29837.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/geo3k_2101.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/geo170k_qa_converted_67833.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/geo170k_align_converted_60252.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4o_dataset.jsonl
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4v-coco-50k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4v-knowledge-2k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4v-llava-30k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4v-sam-20k.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_CLEVR-Math_5290.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_FigureQA_17597.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_Geometry3K_9734.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_GeoQA+_17172.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_GEOS_508.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_IconQA_22599.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_MapQA_5235.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_PlotQA_5485.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_PMC-VQA_35958.json
    sampling_strategy: "first:1%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_Super-CLEVR_8652.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_TabMWP_22462.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_TQA_10181.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_UniGeo_11959.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_VizWiz_6614.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_VQA-AS_5907.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/MathV360K_VQA-RAD_2130.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/magpie_pro_qwen2_72b_st_300000_sp_token_fltd_299992.json
    sampling_strategy: "end:20%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/magpie_pro_l3_80b_st_300000.json
    sampling_strategy: "end:20%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/magpie_pro_l3_80b_mt_300000_sp_token_fltd_299998.json
    sampling_strategy: "end:20%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/image_textualization_dataset_filtered.json
    sampling_strategy: "first:20%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/ai2d_llava_format_2434.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/chart2text_26961.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/chartqa_18265_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/diagram_image_to_text_300.json
    sampling_strategy: "all"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/hateful_memes_8500_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/hitab_2500_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/iam_5663.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/infographic_vqa_2118_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/intergps_1280_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/mapqa_37417_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/rendered_text_10000.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/robut_sqa_8514.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/robut_wikisql_74989.json
    sampling_strategy: "first:10%"
  # - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/robut_wtq_38246_llava_format_filtered_4000tokens_38236.json
  #   sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/screen2words_15730.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/tabmwp_22722.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/tallyqa_98680_llava_format.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/st_vqa_17247_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/tqa_llava_format_27307.json
    sampling_strategy: "first:5%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/visual7w_llava_format_14366.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/visualmrc_3027.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/vqarad_313_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/vsr_2157_llava_format.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/vistext_9969.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/cauldron/websight_10000.json
    sampling_strategy: "first:10%"
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llava_ofa_DEMON-FULL_filtered_311085.json # released in lmms-lab/M4-Instruct
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/llava_ofa_mantis-instruct_reformatted.json # released in lmms-lab/M4-Instruct
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/academic_source_30s_v1_all.json # will be released in next version of LLaVA-NeXT-Video
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/0718_0_30_s_academic_mc_v0_1_all.json # will be released in next version of LLaVA-NeXT-Video
    sampling_strategy: all
  - json_path: /mnt/bn/vl-research/data/llava_instruct/real_vision_flan/sharegpt4video_255000.json # download from sharegpt4video
    sampling_strategy: all
