### ISSUE TITLE
LLaVA-NeXT 社区交流群 （一群已满，二群已建）

### ISSUE THREAD

**Issue by chmod777john** [LLaVA-VL/LLaVA-NeXT#245]
不是引流，只是考虑到可能大家会有些不构成 issue 的小问题，有个群会比较好。 后续如果官方有需要，我愿意转让群管理
我的微信 dreamingforhope ，若二维码失效可添加我

![image](https://github.com/user-attachments/assets/381898c0-057a-42d7-a98b-c23ff9e3e717)

**Comment by UCASlemontea** [comment]
过期了
