### ISSUE TITLE
How to calculate "Video Detailed Description (Score)" as shown in blogs

### ISSUE THREAD

**Issue by jpWang** [LLaVA-VL/LLaVA-NeXT#26]
Hi, thanks for the great works~!
I just want to ask that in this [blog](https://llava-vl.github.io/blog/2024-04-30-llava-next-video/), it contains a "Video Detailed Description (Score)" metric. How to get or calculate it? 
Thanks~!

**Comment by ZhangYuanhan-AI** [comment]
Please refer there: https://github.com/LLaVA-VL/LLaVA-NeXT/blob/video_inference/llava/eval/evaluate_benchmark_video_detail_description.py
