### ISSUE TITLE
About the demo in LLaVA_OneVision_Tutorials.ipynb

### ISSUE THREAD

**Issue by JohnMiao1** [LLaVA-VL/LLaVA-NeXT#268]

**Comment by JuzhengMiao** [comment]
> This is a great and very interesting work. However, when I try the demo in the "LLaVA_OneVision_Tutorials.ipynb" file, I encountered a problem, that is "ValueError: Tokenizer class Qwen2Tokenizer does not exist or is not currently imported.". This problem happeded when running the load_pretrained_model function. Could you please provide any comments on how to solve this problem?

Finally, I found that this is caused by the lower version of transformers. So this is not an issue anymore.
