### ISSUE TITLE
Number of video frames used for training "llama-onevision-qwen2-7b-ov", "LLaVA-Video-7B-Qwen2", and "LLaVA-Video-72B-Qwen2"?

### ISSUE THREAD

**Issue by dcahn12** [LLaVA-VL/LLaVA-NeXT#292]
Thanks for sharing amazing work!

I have a simple question regarding the training process for the video models. 
Specifically, how many video frames for each video do you use for training the [llama-onevision-qwen2-7b-ov](https://huggingface.co/lmms-lab/llava-onevision-qwen2-7b-ov), [LLaVA-Video-7B-Qwen2](https://huggingface.co/lmms-lab/LLaVA-Video-7B-Qwen2), and [LLaVA-Video-72B-Qwen2](https://huggingface.co/lmms-lab/LLaVA-Video-72B-Qwen2), respectively?

From what I observed in the training scripts, it appears that ["LLaVA-Video-7B-Qwen2"](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/scripts/video/train/SO400M_Qwen2_7B_ov_to_video_am9.sh) uses '110' frames, while ["LLaVA-Video-72B-Qwen2"](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/scripts/video/train/SO400M_Qwen2_72B_ov_to_video_am9.sh) uses '32' frames. Is that correct?

**Comment by ZhangYuanhan-AI** [comment]
we use 64 for LLaVA-Video-7B-Qwen2, 32 for others
