### ISSUE TITLE
How to solve this problem? ValueError: Trying to set a tensor of shape torch.Size([1152, 3, 14, 14]) in "weight" (which has shape torch.Size([1024, 3, 14, 14])), this looks incorrect.

### ISSUE THREAD

**Issue by feng11122233** [LLaVA-VL/LLaVA-NeXT#310]
I was trying to run the quick start code with llava-critic-7b, and then reported this error.
I changed ("mm_vision_tower": "google/siglip-so400m-patch14-384") to ("mm_vision_tower": "openai
/
clip-vit-large-patch14-336") in config.json.
My packages are:
transformers==4.40.1
accelerate==1.0.1
torch==2.1.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12 ==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12 ==11.0.2.54
nvidia-curand-cu12 ==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12 ==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12 ==12.5.40
nvidia-nvtx-cu12==12.1.105
and python==3.11.4

Is there anyone know how to solve it?
Thanks in advance.

**Comment by wuxi-dixi** [comment]
我也遇到了这个问题 请问是怎么解决的

**Comment by fsfwl11406** [comment]
我的vision_tower是本地的"mm_vision_tower": "/data/XXXX/siglip-so400m-patch14-384"但是还是报错，和这个错误一摸一样，使用的是lmms-lab/llava-next-interleave-qwen-7b

**Comment by feng11122233** [comment]
> 我的vision_tower是本地的"mm_vision_tower": "/data/XXXX/siglip-so400m-patch14-384"但是还是报错，和这个错误一摸一样，使用的是lmms-lab/llava-next-interleave-qwen-7b

解决了吗？还没有的话可以把报错信息和环境发出来看看

**Comment by fsfwl11406** [comment]
> 我的"mm_vision_tower":设置在本地下载好的siglip-so400m-patch14-384就会报错，设置原来的 "google/siglip-so400m-patch14-384"能连上网的情况下不报错。下载过程也没问题文件是完整的，疑惑ing

我最后把我原本的代码换成最新的代码框架就没问题了，我之前用的是旧版的代码框架，用的是本地的siglip-so400m-patch14-384。

**Comment by truthstriver** [comment]
是llava的视觉编码器加载逻辑有问题，如果指定路径，他就会直接指定CLIPModel，而不是SigLIPModel。

解决方案：
```python
LLaVA-NeXT-main/llava/model/multimodal_encoder/builder.py
```
把这个文件的Line 17加一行
```python
    return SigLipVisionTower(vision_tower, vision_tower_cfg=vision_tower_cfg, **kwargs)
```
就行。
