### ISSUE TITLE
About performance in Video-MME.

### ISSUE THREAD

**Issue by Leon1207** [LLaVA-VL/LLaVA-NeXT#320]
Thanks for your work!
I would like to ask about the setting in Video-MME of 64 frames.
I reproduce the overall  performance of 68.6 without subtitles with this setting:
`tokenizer, model, image_processor, max_length = load_pretrained_model(pretrained, None, model_name, torch_dtype="bfloat16", device_map=device_map, overwrite_config=overwrite_config) `

But in leaderboard you got an overall performance of 70.6.

**Comment by ZhangYuanhan-AI** [comment]
Hi, I have uploaded the logging: https://drive.google.com/drive/folders/1x_ufBQJmAd-8hxgr0er1T1yP_4SNbLd4?usp=sharing

**Comment by Leon1207** [comment]
Thanks for your kindly sharing!
