### ISSUE TITLE
vision tower not updated after finetune

### ISSUE THREAD

**Issue by wenyuqing** [LLaVA-VL/LLaVA-NeXT#345]
Hi, My command is :
```export OMP_NUM_THREADS=8
export NCCL_IB_DISABLE=0
export NCCL_IB_GID_INDEX=3
export NCCL_SOCKET_IFNAME=eth0
export NCCL_DEBUG=INFO

LLM_VERSION="Qwen/Qwen2-7B-Instruct" 
# for 7b model we recommend bs=1, accum=2, 16 nodes, 128 gpus, lr=1e-5, warmup=0.03
# for 72b model we recommend bs=1, accum=1, 32 nodes, 256 gpus, lr=1e-5, warmup=0.03
LLM_VERSION_CLEAN="${LLM_VERSION//\//_}"
VISION_MODEL_VERSION="google/siglip-so400m-patch14-384"
VISION_MODEL_VERSION_CLEAN="${VISION_MODEL_VERSION//\//_}"

############### Pretrain ################

BASE_RUN_NAME="llavanext-google_siglip-so400m-patch14-384-Qwen_Qwen2-7B-Instruct-mlp2x_gelu-pretrain_blip558k_plain"
echo "BASE_RUN_NAME: ${BASE_RUN_NAME}"

############### Finetune ################

# Stage 2
PROMPT_VERSION="qwen_1_5"
RUN_NAME="debug-robot-lr1e5-llava-onevision-${VISION_MODEL_VERSION_CLEAN}-${LLM_VERSION_CLEAN}-ov_stage_am9" 
# PREV_STAGE_CHECKPOINT="/mnt/bn/vl-research/checkpoints/onevision/llavanext-google_siglip-so400m-patch14-384-Qwen_Qwen2-7B-Instruct-mid_to_final_next_3m_am9_july14" # replace it with your last checkpoint training from single image collection
PREV_STAGE_CHECKPOINT="/data/code/LLaVA-NeXT/ckpts/llava-onevision-qwen2-7b-ov"
echo "PREV_STAGE_CHECKPOINT: ${PREV_STAGE_CHECKPOINT}"
echo "MID_RUN_NAME: ${RUN_NAME}"

OUTPUT_BASE=/mnt/wyqrobot/llava-next-robot/

ACCELERATE_CPU_AFFINITY=1 torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port="29501" \
    llava/train/train_robot.py \
    --deepspeed scripts/zero3.json \
    --model_name_or_path $PREV_STAGE_CHECKPOINT \
    --version $PROMPT_VERSION \
    --data_path MYDATASET
    --image_folder /mnt/bn/vl-research/data/llava_data \
    --video_folder /mnt/bn/vl-research/data/llava_video \
    --mm_tunable_parts="mm_vision_tower,mm_mlp_adapter,mm_language_model" \
    --mm_vision_tower_lr=2e-6 \
    --vision_tower ${VISION_MODEL_VERSION} \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --group_by_modality_length True \
    --image_aspect_ratio anyres_max_9 \
    --image_grid_pinpoints  "(1x1),...,(6x6)" \
    --mm_patch_merge_type spatial_unpad \
    --bf16 True \
    --run_name $RUN_NAME \
    --output_dir $OUTPUT_BASE/$RUN_NAME \
    --num_train_epochs 3 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 32768 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb \
    --torch_compile True \
    --torch_compile_backend "inductor" \
    --dataloader_drop_last True \
    --frames_upbound 32
exit 0;

# You can delete the sdpa attn_implementation if you want to use flash attn
```
When I load my fine-tuned model for inference, I found that the vision tower exactly is the same as in  the pretrained llava-sonevision ckpt: _llava-onevision-qwen2-7b-ov_
I have already set mm_tunable_parts="mm_vision_tower,mm_mlp_adapter,mm_language_model" , what's the possible problem?  I'm looking forward to your warm help!

**Comment by zihaolucky** [comment]
Because the code initialize the vision model from `vision_tower ${VISION_MODEL_VERSION}`, it is the origin one for sure, not the finetuned version as you expect. cc @Luodian

**Comment by zihaolucky** [comment]
check this method in builder.py

```python
def load_pretrained_model(model_path, model_base, model_name, load_8bit=False, load_4bit=False, device_map="auto", attn_implementation="flash_attention_2", customized_config=None, overwrite_config=None, **kwargs):
    kwargs["device_map"] = device_map
```

**Comment by jun0wanan** [comment]
> Hi, My command is :
> 
> ```
> export NCCL_IB_DISABLE=0
> export NCCL_IB_GID_INDEX=3
> export NCCL_SOCKET_IFNAME=eth0
> export NCCL_DEBUG=INFO
> 
> LLM_VERSION="Qwen/Qwen2-7B-Instruct" 
> # for 7b model we recommend bs=1, accum=2, 16 nodes, 128 gpus, lr=1e-5, warmup=0.03
> # for 72b model we recommend bs=1, accum=1, 32 nodes, 256 gpus, lr=1e-5, warmup=0.03
> LLM_VERSION_CLEAN="${LLM_VERSION//\//_}"
> VISION_MODEL_VERSION="google/siglip-so400m-patch14-384"
> VISION_MODEL_VERSION_CLEAN="${VISION_MODEL_VERSION//\//_}"
> 
> ############### Pretrain ################
> 
> BASE_RUN_NAME="llavanext-google_siglip-so400m-patch14-384-Qwen_Qwen2-7B-Instruct-mlp2x_gelu-pretrain_blip558k_plain"
> echo "BASE_RUN_NAME: ${BASE_RUN_NAME}"
> 
> ############### Finetune ################
> 
> # Stage 2
> PROMPT_VERSION="qwen_1_5"
> RUN_NAME="debug-robot-lr1e5-llava-onevision-${VISION_MODEL_VERSION_CLEAN}-${LLM_VERSION_CLEAN}-ov_stage_am9" 
> # PREV_STAGE_CHECKPOINT="/mnt/bn/vl-research/checkpoints/onevision/llavanext-google_siglip-so400m-patch14-384-Qwen_Qwen2-7B-Instruct-mid_to_final_next_3m_am9_july14" # replace it with your last checkpoint training from single image collection
> PREV_STAGE_CHECKPOINT="/data/code/LLaVA-NeXT/ckpts/llava-onevision-qwen2-7b-ov"
> echo "PREV_STAGE_CHECKPOINT: ${PREV_STAGE_CHECKPOINT}"
> echo "MID_RUN_NAME: ${RUN_NAME}"
> 
> OUTPUT_BASE=/mnt/wyqrobot/llava-next-robot/
> 
> ACCELERATE_CPU_AFFINITY=1 torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port="29501" \
>     llava/train/train_robot.py \
>     --deepspeed scripts/zero3.json \
>     --model_name_or_path $PREV_STAGE_CHECKPOINT \
>     --version $PROMPT_VERSION \
>     --data_path MYDATASET
>     --image_folder /mnt/bn/vl-research/data/llava_data \
>     --video_folder /mnt/bn/vl-research/data/llava_video \
>     --mm_tunable_parts="mm_vision_tower,mm_mlp_adapter,mm_language_model" \
>     --mm_vision_tower_lr=2e-6 \
>     --vision_tower ${VISION_MODEL_VERSION} \
>     --mm_projector_type mlp2x_gelu \
>     --mm_vision_select_layer -2 \
>     --mm_use_im_start_end False \
>     --mm_use_im_patch_token False \
>     --group_by_modality_length True \
>     --image_aspect_ratio anyres_max_9 \
>     --image_grid_pinpoints  "(1x1),...,(6x6)" \
>     --mm_patch_merge_type spatial_unpad \
>     --bf16 True \
>     --run_name $RUN_NAME \
>     --output_dir $OUTPUT_BASE/$RUN_NAME \
>     --num_train_epochs 3 \
>     --per_device_train_batch_size 8 \
>     --per_device_eval_batch_size 4 \
>     --gradient_accumulation_steps 2 \
>     --evaluation_strategy "no" \
>     --save_strategy "steps" \
>     --save_steps 1000 \
>     --save_total_limit 1 \
>     --learning_rate 1e-5 \
>     --weight_decay 0. \
>     --warmup_ratio 0.03 \
>     --lr_scheduler_type "cosine" \
>     --logging_steps 1 \
>     --tf32 True \
>     --model_max_length 32768 \
>     --gradient_checkpointing True \
>     --dataloader_num_workers 4 \
>     --lazy_preprocess True \
>     --report_to wandb \
>     --torch_compile True \
>     --torch_compile_backend "inductor" \
>     --dataloader_drop_last True \
>     --frames_upbound 32
> exit 0;
> 
> # You can delete the sdpa attn_implementation if you want to use flash attn
> ```
> 
> When I load my fine-tuned model for inference, I found that the vision tower exactly is the same as in the pretrained llava-sonevision ckpt: _llava-onevision-qwen2-7b-ov_ I have already set mm_tunable_parts="mm_vision_tower,mm_mlp_adapter,mm_language_model" , what's the possible problem? I'm looking forward to your warm help!

您好您这个是怎么解决的？

**Comment by GaetanoDibenedetto** [comment]
How do you solve this?

**Comment by alcholiclg** [comment]
> When I load my fine-tuned model for inference, I found that the vision tower exactly is the same as in the pretrained llava-sonevision ckpt: _llava-onevision-qwen2-7b-ov_
Did you known the answer now?
