### ISSUE TITLE
How many GPUs were used?

### ISSUE THREAD

**Issue by lerogo** [LLaVA-VL/LLaVA-NeXT#370]
Hi,
Thank you very much for your outstanding work, I have a question to ask:

**What is the final batchsize? (num_gpu * batch_size_per_device * accumulation_steps). Including pretrain and fintune**

https://github.com/LLaVA-VL/LLaVA-NeXT/blob/79ef45a6d8b89b92d7a8525f077c3a3a9894a87d/scripts/train/direct_finetune_clip.sh#L42

Looking forward to your reply
Thanks

**Comment by HuangChiEn** [comment]
> Hi, Thank you very much for your outstanding work, I have a question to ask:
> 
> **What is the final batchsize? (num_gpu * batch_size_per_device * accumulation_steps). Including pretrain and fintune**
> 
> [LLaVA-NeXT/scripts/train/direct_finetune_clip.sh](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/79ef45a6d8b89b92d7a8525f077c3a3a9894a87d/scripts/train/direct_finetune_clip.sh#L42)
> 
> Line 42 in [79ef45a](/LLaVA-VL/LLaVA-NeXT/commit/79ef45a6d8b89b92d7a8525f077c3a3a9894a87d)
> 
>  --per_device_train_batch_size 4 \ 
> Looking forward to your reply Thanks

Hi, have you figure out the batch size for direct_finetune_clip.sh ?
