### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [LLaVA-VL/LLaVA-NeXT#4]
Copy pasted the example from here: https://github.com/LLaVA-VL/LLaVA-NeXT/blob/inference/docs/LLaVA-NeXT.md

Get this:

```
Loading checkpoint shards: 100%|█████████████████████████████| 4/4 [00:02<00:00,  1.50it/s]
Traceback (most recent call last):
  File "/home/user/Programs/LLaVA/test.py", line 36, in <module>
    cont = model.generate(
  File "/home/user/Programs/LLaVA/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/Programs/LLaVA/llava/model/language_model/llava_llama.py", line 113, in generate
    (inputs, position_ids, attention_mask, _, inputs_embeds, _) = self.prepare_inputs_labels_for_multimodal(inputs, position_ids, attention_mask, None, None, images, image_sizes=image_sizes)
  File "/home/user/Programs/LLaVA/llava/model/llava_arch.py", line 199, in prepare_inputs_labels_for_multimodal
    raise ValueError("vision_tower_image_size is not found in the vision tower.")
ValueError: vision_tower_image_size is not found in the vision tower.
```

`git log` shows me at:

```
commit 9496e2d4667a220a3d70c268bb30bf9ed2ced724 (HEAD, next/inference)
Author: ZhangYuanhan-AI <yuanhan002@ntu.edu.sg>
Date:   Fri May 10 05:24:02 2024 +0000

    Fix file paths and scaling factor calculation in video_demo.py and video_demo.sh
```

**Comment by kcz358** [comment]
Hi @AmericanPresidentJimmyCarter,  I have fixed the bugs. Please try again.

**Comment by AmericanPresidentJimmyCarter** [comment]
Ok I get this thanks: 

> ['\nThe image shows a radar chart, also known as a spider chart or a web chart, which is a type of graph used to display multivariate data in the form of a two-dimensional chart of three or more quantitative variables represented on axes starting from the same point. Each axis represents a different variable, and the values are plotted along each axis and connected to form a polygon.\n\nIn this particular radar chart, there are several axes labeled with different variables, such as "MM-Vet," "LLaVA-Bench," "SEED-Bench," "MMBench-CN," "MMBench," "TextVQA," "VizWiz," "GQA," "BLIP-2," "InstructBLIP," "Owen-VL-Chat," and "LLaVA-1.5." These labels suggest that the chart is comparing the performance of different models or systems across various benchmarks or tasks, such as machine translation, visual question answering, and text-based question answering.\n\nThe chart is color-coded, with each color representing a different model or system. The points on the chart are connected to form a polygon, which shows the relative performance of each model across the different benchmarks. The closer the point is to the outer edge of the']
