### ISSUE TITLE
How to load the largest models?

### ISSUE THREAD

**Issue by jeffhernandez1995** [LLaVA-VL/LLaVA-NeXT#53]
Loading `lmms-lab/llava-next-72b` and `lmms-lab/llava-next-110b` with the device_map='auto' does not seems to work and results in `NotImplementedError: Cannot copy out of meta tensor; no data!`, even though I am trying to load the model on 8-40GB GPUs. Is there a minimal example to do inference on the largest models?

**Comment by claudius-kienle** [comment]
What worked for me was to manually set the device_map like following

```python
    device = "cuda"
    device_map = {
        "model.vision_tower": "cuda:1",
        "model.vision_resampler": "cuda:1",
        "model.mm_projector": "cuda:1",
        "model.norm": "cuda:1",
        "model.image_newline": "cuda:1",
        "model.embed_tokens": "cuda:1",
        "lm_head": "cuda:1",
    }
    for i in range(0, 40):
        device_map["model.layers.%d" % i] = "cuda:1"
    for i in range(40, 81):
        device_map["model.layers.%d" % i] = "cuda:2"
```

This loads half of the Qwen LLM on gpu1 and the other half on gpu2

**Comment by jeffhernandez1995** [comment]
I managed it make it run by directly calling the class instead of using the `load_pretrained_model` function:
```
tokenizer = AutoTokenizer.from_pretrained(model_pth, use_fast=False)

model = LlavaQwenForCausalLM.from_pretrained(
    model_pth,
    low_cpu_mem_usage=True,
    attn_implementation="flash_attention_2",
    torch_dtype=TORCH_TYPE,
    device_map='auto',
)
```

**Comment by jacktkk** [comment]
> What worked for me was to manually set the device_map like following

Hi, in the case of model segmentation, which device should the data be placed on? I'm getting the following error.

Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:0!

**Comment by ChipsICU** [comment]
> > What worked for me was to manually set the device_map like following
> 
> Hi, in the case of model segmentation, which device should the data be placed on? I'm getting the following error.
> 
> Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:0!

for me, use default code is ok, remember not set CUDA_VISIBLE_DEVICES

**Comment by zshyang** [comment]
> > What worked for me was to manually set the device_map like following
> 
> Hi, in the case of model segmentation, which device should the data be placed on? I'm getting the following error.
> 
> Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:0!

I have the same issue. Is your quetion get resolved in the end?
