### ISSUE TITLE
What is the conv-mode for LLaVA-NeXT-Video-7B-32K

### ISSUE THREAD

**Issue by rebuttalpapers** [LLaVA-VL/LLaVA-NeXT#54]
I tried the following conv-mode:
vicuna_v1
--conv-mode mistral_direct
Llava_llama_2
llama_2
mistral_instruct

and encounter the error as below:
AttributeError: 'LlavaMistralConfig' object has no attribute 'attention_bias'

**Comment by ZhangYuanhan-AI** [comment]
Hi, what is the version of your transformers?

**Comment by rebuttalpapers** [comment]
Thanks!
>>> import transformers
>>> print(transformers.__version__)
4.40.0.dev0

**Comment by ZhangYuanhan-AI** [comment]
My TF version is 4.39.0 and the conv model should be mistral_direct for LLaVA-NeXT-Video-7B-32K

**Comment by rebuttalpapers** [comment]
Thanks @ZhangYuanhan-AI !

What is the "attention_dropout" and how it solves the problem above "AttributeError: 'LlavaMistralConfig' object has no attribute 'attention_bias'"?

Additionally, I downgraded the TF from 4.40.0.dev0 to 4.39.0 and the same problem is still there.

**Comment by ZhangYuanhan-AI** [comment]
https://github.com/LLaVA-VL/LLaVA-NeXT/blob/6944062b9bb2e61c48436f1a65c3ea339095ec91/playground/demo/video_demo.py#L160

try to change this line to 

output_ids = model.generate(inputs=input_ids, images=video, attention_mask=attention_masks, modalities="video", do_sample=True, temperature=0.2, max_new_tokens=1024, use_cache=True)
