### ISSUE TITLE
Was CLIP ViT-L/14 Freezed in LLaVA-NeXT-Video-DPO (7B)

### ISSUE THREAD

**Issue by jongwoopark7978** [LLaVA-VL/LLaVA-NeXT#66]
Hi team,

I am currently using LLaVA-NeXT-Video-DPO (7B) and I want to confirm if it uses the pre-trained CLIP ViT-L/14. During training, do you freeze the visual encoder in the same way as in llava1.5? I ask because I hope to use the CLIP text encoder to measure the similarity btw visual and text tokens.

**Comment by ZhangYuanhan-AI** [comment]
Yes, it was freezed.

**Comment by jongwoopark7978** [comment]
Thank you for your quick answer.

**Comment by Wang-Xiaodong1899** [comment]
Hi @ZhangYuanhan-AI , you said that visual encoder is frozen, but `model.safetensors.index.json` in LLaVA-NeXT-Video-DPO(7B) contains the `vision_tower` keys like following:
![image](https://github.com/user-attachments/assets/0f872f88-8742-4c10-ad2a-0e2ced76031d)


So I'm a little confused, what parts are trainable when it comes to training LLaVA-NeXT-Video-DPO(7B)?

Would you mind share the hyper-parameters used to train LLaVA-NeXT-Video-DPO(7B)?

Thanks a lot!

**Comment by ZhangYuanhan-AI** [comment]
The ckpt is the same as the original CLIP weights
