### ISSUE TITLE
Unable to load interleave model 

### ISSUE THREAD

**Issue by justinphen** [LLaVA-VL/LLaVA-NeXT#83]
When I was trying to run the gradio demo with the new llava-next-interleave-7b model, I ran into the following two errors. Any ideas?
<img width="1243" alt="Screenshot 2024-06-28 at 15 15 57" src="https://github.com/LLaVA-VL/LLaVA-NeXT/assets/145513801/380034f9-d635-48c4-a0c7-68d6eaaf7a64">

**Comment by HaoZhang534** [comment]
> When I was trying to run the gradio demo with the new llava-next-interleave-7b model, I ran into the following two errors. Any ideas? <img alt="Screenshot 2024-06-28 at 15 15 57" width="1243" src="https://private-user-images.githubusercontent.com/145513801/344200036-380034f9-d635-48c4-a0c7-68d6eaaf7a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzE2MzUsIm5iZiI6MTcxOTYzMTMzNSwicGF0aCI6Ii8xNDU1MTM4MDEvMzQ0MjAwMDM2LTM4MDAzNGY5LWQ2MzUtNDhjNC1hMGM3LTY4ZDZlYWFmN2E2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwMzIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGY3ZDJiZTdlNmRhMWM3Y2FkNGUzNTUwOTIwZjE2NDNlMTkzZjRjN2I0NDFjNjcwMTViYzBkMzc0ZmI1Zjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iCDIrFUzvbflNVw32WrrQLeYYWleg3T9BlJCtYp04lg">

You need to install llava-next first.

**Comment by justinphen** [comment]
> > When I was trying to run the gradio demo with the new llava-next-interleave-7b model, I ran into the following two errors. Any ideas? <img alt="Screenshot 2024-06-28 at 15 15 57" width="1243" src="https://private-user-images.githubusercontent.com/145513801/344200036-380034f9-d635-48c4-a0c7-68d6eaaf7a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzE2MzUsIm5iZiI6MTcxOTYzMTMzNSwicGF0aCI6Ii8xNDU1MTM4MDEvMzQ0MjAwMDM2LTM4MDAzNGY5LWQ2MzUtNDhjNC1hMGM3LTY4ZDZlYWFmN2E2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwMzIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGY3ZDJiZTdlNmRhMWM3Y2FkNGUzNTUwOTIwZjE2NDNlMTkzZjRjN2I0NDFjNjcwMTViYzBkMzc0ZmI1Zjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iCDIrFUzvbflNVw32WrrQLeYYWleg3T9BlJCtYp04lg">
> 
> You need to install llava-next first.

The thing is, I have already installed llava-next before running this file. So not sure what caused this problem...

**Comment by jinsikbang** [comment]
If you install flash attention module, then might be solved.
