### ISSUE TITLE
Demo deployment issues

### ISSUE THREAD

**Issue by pedrocolon93** [LLaVA-VL/LLaVA-NeXT#85]
Hi there! I clone the tensors here:
git clone https://huggingface.co/lmms-lab/llava-next-interleave-7b
And I do the setup as is in the readme (which needs an upgrade for gradio (pip install --upgrade gradio) and needs numpy==1.23.0) and when i do inference in gradio (with the examples) I get garbage. 
Is there anything I am missing? 
![image](https://github.com/LLaVA-VL/LLaVA-NeXT/assets/5157240/39cb3690-a446-4fba-aa97-002e612856b5)

**Comment by pedrocolon93** [comment]
As a side note also needs to install flash attention: pip install flash-attn

**Comment by pedrocolon93** [comment]
As a second side note same thing for the -dpo model.

**Comment by pedrocolon93** [comment]
FIxed this by cloning the repo and adding -qwen- in the name of the repo... Otherwise it loads some other Llava architecture which does not work.

**Comment by pedrocolon93** [comment]
If loading in 4 bit, the line in builder.py
        kwargs["load_in_4bit"] = True
needs to be commented.

**Comment by HaoZhang534** [comment]
You should change the model path from llava-next-interleave-7b to llava-next-interleave-qwen-7b and try again.

**Comment by pedrocolon93** [comment]
Thanks, and double check the:
 If loading in 4 bit, the line in builder.py
`kwargs["load_in_4bit"] = True
`needs to be commented 
and adding in the flash-attn dependency
