### ISSUE TITLE
How many A100s used for training?

### ISSUE THREAD

**Issue by syspider** [LLaVA-VL/LLaVA-NeXT#87]
Thank you for the great job!
I am just a bit curious about the computing resources used for LLaVA-NeXT.

**Comment by k-nearest-neighbor** [comment]
[The largest 34B variant finishes training in ~1 day with 32 A100s according to the blog post](https://llava-vl.github.io/blog/2024-01-30-llava-next/#:~:text=The%20largest%2034B%20variant%20finishes%20training%20in%20~1%20day%20with%2032%20A100s)
