### ISSUE TITLE
question about the demo implementation

### ISSUE THREAD

**Issue by DavidYan2001** [LLaVA-VL/LLaVA-NeXT#92]
Hi, thanks for the outstanding work!

I have downloaded the model files for llava-next-interleave-7b and siglip-so400m-patch14-384 When I try to run "python playground/demo/interleave_demo.py --model_path XXX/LLaVA-NeXT/checkpoints/llava-next-interleave-7b", it is noticed that "ValueError: Model llava-next-interleave-7b not supported". 

I go into the code and find that the model we initialize does not match the params in the model files:
<img width="1551" alt="截屏2024-07-02 00 16 10" src="https://github.com/LLaVA-VL/LLaVA-NeXT/assets/139680304/f7b4c977-e254-423c-a24e-792668db863e">

Then I find in the code that 
<img width="1403" alt="截屏2024-07-02 00 17 26" src="https://github.com/LLaVA-VL/LLaVA-NeXT/assets/139680304/d8426628-eda6-4955-b181-a16278871c0f">

In this builder function, it turns to initialize the model with ClipVisionTower, but what we want is the SigLipVisionTower; thus I mannually choose to set up as SigLipVisionTower, leading to new problems:
<img width="803" alt="截屏2024-07-02 00 22 08" src="https://github.com/LLaVA-VL/LLaVA-NeXT/assets/139680304/08823ac8-045e-43bd-b96a-7cb250c08065">
<img width="1153" alt="截屏2024-07-02 00 23 11" src="https://github.com/LLaVA-VL/LLaVA-NeXT/assets/139680304/037a8519-bb65-4514-925b-260ffddd9a0e">

In the corresponding code, I find that the shape of output_ids[0, -keyword_id.shape[0] :] and keyword_id are different, with 2 for output_ids[0, -keyword_id.shape[0] :] and 3 for keyword_id. I have no idea how to solve this or the previous problem with SigLipVisionTower; Could you please help?

Thanks a lot!!

**Comment by HaoZhang534** [comment]
You should change the model path from llava-next-interleave-7b to llava-next-interleave-qwen-7b and try again.

**Comment by zihaolucky** [comment]
Hi @HaoZhang534 I don't think change the model path change this issue, the code meets `is_absolute_path_exists=True` and use CLIPVisionTower. So I have to put the `siglip` condition first and fixed the problem.

BTW change to `qwen` helps in another place.
