### ISSUE TITLE
Eval Results

### ISSUE THREAD

**Issue by liguopeng0923** [LLaVA-VL/LLaVA-NeXT#96]
Hi,

I have reproduced successfully your code with 7B-dpo model. But some results are lower than your reported results. Is it normal?

<img width="1407" alt="image" src="https://github.com/LLaVA-VL/LLaVA-NeXT/assets/61257834/b954760f-ffee-4e01-af16-08b93eddb386">

**Comment by ZrrSkywalker** [comment]
@liguopeng0923

**Comment by liguopeng0923** [comment]
Thanks, I will reproduce it soon.

**Comment by zihaolucky** [comment]
Hi @liguopeng0923 do you change the code in processing multi-image inputs?

ref to https://github.com/LLaVA-VL/LLaVA-NeXT/issues/90#issuecomment-2217722628

**Comment by liguopeng0923** [comment]
Hi @zihaolucky , 

Actually not, i use this script for eval. https://github.com/LLaVA-VL/LLaVA-NeXT/blob/inference/scripts/interleave/eval_all.sh

**Comment by zihaolucky** [comment]
> Hi @zihaolucky ,
> 
> Actually not, i use this script for eval. https://github.com/LLaVA-VL/LLaVA-NeXT/blob/inference/scripts/interleave/eval_all.sh

Oh, so `llava-next-interleave` series might not adopt the `AnyRes` way to split one image to multiple patches. @zrrs
could you confirm this? Thanks
